"""cambiado en resuemn

Revision ID: 26769210c971
Revises: 27f0138f3fd9
Create Date: 2021-02-15 16:45:00.486942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26769210c971'
down_revision = '27f0138f3fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumen', sa.Column('caja_actualizada', sa.Boolean(), nullable=True))
    op.drop_column('resumen', 'caja_entregada')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumen', sa.Column('caja_entregada', sa.BOOLEAN(), nullable=True))
    op.drop_column('resumen', 'caja_actualizada')
    # ### end Alembic commands ###
