"""nuevo parametro

Revision ID: 27f0138f3fd9
Revises: 9fd715290b4b
Create Date: 2021-02-14 21:49:53.222972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f0138f3fd9'
down_revision = '9fd715290b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ultimo_login_diario', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ultimo_login_diario')
    # ### end Alembic commands ###
