"""tables created

Revision ID: 58ff8f222e19
Revises: 
Create Date: 2021-01-30 19:58:46.370659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ff8f222e19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=120), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('billetes', sa.String(length=18), nullable=True),
    sa.Column('tipo', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operaciones_fecha'), 'operaciones', ['fecha'], unique=False)
    op.create_index(op.f('ix_operaciones_tipo'), 'operaciones', ['tipo'], unique=False)
    op.create_table('resumen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('cambio', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumen_fecha'), 'resumen', ['fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumen_fecha'), table_name='resumen')
    op.drop_table('resumen')
    op.drop_index(op.f('ix_operaciones_tipo'), table_name='operaciones')
    op.drop_index(op.f('ix_operaciones_fecha'), table_name='operaciones')
    op.drop_table('operaciones')
    # ### end Alembic commands ###
