"""campo de vaciado de caja

Revision ID: 63018563d763
Revises: eabc3e14ab7d
Create Date: 2021-02-13 20:52:21.623388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63018563d763'
down_revision = 'eabc3e14ab7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumen', sa.Column('caja_entregada', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumen', 'caja_entregada')
    # ### end Alembic commands ###
