"""nuevo campo en resumen

Revision ID: e0e17fccefa0
Revises: 58ff8f222e19
Create Date: 2021-02-05 20:48:51.964098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e17fccefa0'
down_revision = '58ff8f222e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumen', sa.Column('balance_billetes', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumen', 'balance_billetes')
    # ### end Alembic commands ###
