"""agregado campo de monedas en operacion

Revision ID: eabc3e14ab7d
Revises: e0e17fccefa0
Create Date: 2021-02-13 19:45:21.969000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabc3e14ab7d'
down_revision = 'e0e17fccefa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operaciones', sa.Column('monedas', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operaciones', 'monedas')
    # ### end Alembic commands ###
